on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Build - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest

          - os_name: macOS-arm64
            os: macOS-latest


    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain if not cross-compiling
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        shell: bash
        run: |
          cargo build --locked --release
      
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sm_connect-${{ matrix.platform.os_name }}
          path: target/release/sm_connect


  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: sm_connect-*
          path: release_files/
      - run: ls -l release_files/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_files/sm_connect-*

